# Generated by Django 3.1.1 on 2020-09-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=100)),
                ('done', models.BooleanField()),
            ],
        ),
    ]
